#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = mouse mouse-boot

srcdir = .
top_srcdir = ../../../..
subdir = hid

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
