#
# Makefile for minixfs documentation
#
SHELL = /bin/sh
SUBDIRS =

srcdir = .
top_srcdir = ../..
subdir = docs

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here:

# default overwrites

# default definitions

