
#ifndef _xa_types_h
/** RGB intesities in promille */
typedef struct rgb_1000
{
	short  red;    /**< Red-Intensity in range [0..1000] */
 	short  green;  /**< Green-Intensity in range [0..1000] */
 	short  blue;   /**< Blue-Intensity in range [0..1000] */
} RGB1000;

struct xa_gradient
{
	unsigned long allocs;
	short wmask, hmask;
	short w, h;
	short method;
	short n_steps;
	short steps[8];
	struct rgb_1000 c[16];
};
#endif

#define START 0x1111
#define STOP  0x1112
#define GRAD_INIT 0x00ff

enum {

	OTOP_VSLIDE_GRADIENT = GRAD_INIT,
	OTOP_HSLIDE_GRADIENT,
	OTOP_VSLIDER_GRADIENT,
	OTOP_HSLIDER_GRADIENT,
	UTOP_VSLIDE_GRADIENT,
	UTOP_HSLIDE_GRADIENT,
	UTOP_VSLIDER_GRADIENT,
	UTOP_HSLIDER_GRADIENT,
	OTOP_TITLE_GRADIENT,
	UTOP_TITLE_GRADIENT,
	OTOP_INFO_GRADIENT,
	UTOP_INFO_GRADIENT,
	OTOP_GREY_GRADIENT,
	UTOP_GREY_GRADIENT,

	ALERT_OTOP_TITLE_GRADIENT,
	ALERT_UTOP_TITLE_GRADIENT,
	ALERT_UTOP_GREY_GRADIENT,

	SLIST_OTOP_VSLIDE_GRADIENT,
	SLIST_OTOP_HSLIDE_GRADIENT,
	SLIST_OTOP_VSLIDER_GRADIENT,
	SLIST_OTOP_HSLIDER_GRADIENT,
	SLIST_UTOP_VSLIDE_GRADIENT,
	SLIST_UTOP_HSLIDE_GRADIENT,
	SLIST_UTOP_VSLIDER_GRADIENT,
	SLIST_UTOP_HSLIDER_GRADIENT,
	SLIST_OTOP_TITLE_GRADIENT,
	SLIST_UTOP_TITLE_GRADIENT,
	SLIST_OTOP_INFO_GRADIENT,
	SLIST_UTOP_INFO_GRADIENT,
	SLIST_OTOP_GREY_GRADIENT,
	SLIST_UTOP_GREY_GRADIENT,

	MENU_GRADIENT,
	SEL_TITLE_GRADIENT,
	SEL_POPENT_GRADIENT,
	INDBUTT_GRADIENT,
	SEL_INDBUTT_GRADIENT,
	ACTBUTT_GRADIENT,
	POPBKG_GRADIENT
};

