#
# Makefile for xaaes
#

SHELL = /bin/sh
SUBDIRS = src.km

srcdir = .
top_srcdir = ..
subdir = xaaes

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here:

# default overwrites

# default definitions

help 000 02060 deb col all-kernels:
	$(MAKE) -C src.km $@

ara:: 02060
	@:

mil:: 02060
	@:

hat:: 000
	@:

hat030:: 02060
	@:

080:: 02060
	@:
