#
# Makefile for $(CPU) object modules
#

SHELL = /bin/sh
SUBDIRS = 

srcdir = ..
top_srcdir = ../..
subdir = .cpu_$(CPU)

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: objs

# default overwrites
cflags = $(kernel_cflags)
nocflags = $(kernel_nocflags)

# default definitions
OBJS = $(COBJS:.c=.o)

VPATH = ..

objs: $(OBJS)
	echo $(OBJS) > $@


# default dependencies
# must be included last
include $(top_srcdir)/DEPENDENCIES
