
# include "global.h"
# include "version.h"


ushort native_utc = 0;

UNIT error;

SI *super_ptr[NUM_DRIVES];
FILEPTR *firstptr;
struct kerinfo *kernel;

long mfs_magic = MFS_MAGIC;

int mfs_maj = MFS_MAJOR;
int mfs_min = MFS_MINOR;
int mfs_plev = 0;

long fs_mode[NUM_DRIVES] =
{
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
	TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT, TRANS_DEFAULT,
};
