#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = whlmoose

srcdir = .
top_srcdir = ..
subdir = adi

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
