#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = audio dsp56k flop-raw lp mfp nfstderr nfcdrom scc skeleton uart xconout2

srcdir = .
top_srcdir = ..
subdir = xdd

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
