#
# Makefile for usb
#

SHELL = /bin/sh
SUBDIRS = src.km

srcdir = .
top_srcdir = ..
subdir = usb

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here:

# default overwrites

# default definitions
