#
# Makefile for extended filesystems
#

SHELL = /bin/sh
SUBDIRS = aranym ext2fs hostfs minixfs nfs skeleton isofs

srcdir = .
top_srcdir = ..
subdir = xfs

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
