#
# Makefile for extended filesystems
#

SHELL = /bin/sh
SUBDIRS = ext2fs minixfs nfs skeleton

srcdir = .
top_srcdir = ..
subdir = xfs

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
