#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = eth keyboard mouse printer storage

srcdir = .
top_srcdir = ../../..
subdir = udd

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
