#ifndef _mint_dosvecs_h
#define _mint_dosvecs_h

struct shared_lib;
typedef long _cdecl (*SLB_EXEC)(struct shared_lib *sl, long fn, short nargs, ...);
struct dtabuf;
struct xattr;
struct sigaction;
struct stat;
struct timeval;
struct timezone;
struct pollfd;
struct iovec;
struct sockaddr;
struct msghdr;
struct shmid_ds;
union __semun;
struct sembuf;
struct msqid_ds;

/*
 * GEMDOS function dispatcher.
 */
typedef struct {
	long _cdecl (*p_pterm0)(void);
	long _cdecl (*p_c_conin)(void);
	long _cdecl (*p_c_conout)(int c);
	long _cdecl (*p_c_auxin)(void);
	long _cdecl (*p_c_auxout)(int c);
	long _cdecl (*p_c_prnout)(int c);
	long _cdecl (*p_c_rawio)(int c);
	long _cdecl (*p_c_rawcin)(void);
	long _cdecl (*p_c_necin)(void);
	long _cdecl (*p_c_conws)(const char *str);
	long _cdecl (*p_c_conrs)(char *buf);
	long _cdecl (*p_c_conis)(void);
	long _cdecl (*_res_00c)(void);
	long _cdecl (*_res_00d)(void);
	long _cdecl (*p_d_setdrv)(int d);
	long _cdecl (*_res_00f)(void);

	long _cdecl (*p_c_conos)(void);
	long _cdecl (*p_c_prnos)(void);
	long _cdecl (*p_c_auxis)(void);
	long _cdecl (*p_c_auxos)(void);
	long _cdecl (*p_m_addalt)(long start, long size);
	long _cdecl (*p_s_realloc)(long size);
	long _cdecl (*p_s_lbopen)(char *name, char *path, long min_ver, struct shared_lib **sl, SLB_EXEC *fn);
	long _cdecl (*p_s_lbclose)(struct shared_lib *sl);
	long _cdecl (*_res_018)(void);
	long _cdecl (*p_d_getdrv)(void);
	long _cdecl (*p_f_setdta)(struct dtabuf *dta);
	long _cdecl (*_res_01b)(void);
	long _cdecl (*_res_01c)(void);
	long _cdecl (*_res_01d)(void);
	long _cdecl (*_res_01e)(void);
	long _cdecl (*_res_01f)(void);

	long _cdecl (*p_s_uper)(long new_ssp);
	long _cdecl (*_res_021)(void);
	long _cdecl (*_res_022)(void);
	long _cdecl (*_res_023)(void);
	long _cdecl (*_res_024)(void);
	long _cdecl (*_res_025)(void);
	long _cdecl (*_res_026)(void);
	long _cdecl (*_res_027)(void);
	long _cdecl (*_res_028)(void);
	long _cdecl (*_res_029)(void);
	long _cdecl (*p_t_getdate)(void);
	long _cdecl (*p_t_setdate)(ushort date);
	long _cdecl (*p_t_gettime)(void);
	long _cdecl (*p_t_settime)(ushort time);
	long _cdecl (*_res_02e)(void);
	struct dtabuf *_cdecl (*p_f_getdta)(void);

	long _cdecl (*p_s_version)(void);
	long _cdecl (*p_p_termres)(long save, short code);
	long _cdecl (*_res_032)(void);
	long _cdecl (*p_s_config)(void);	/* MagiC: long Sconfig(short subfn, long flags); */
	long _cdecl (*_res_034)(void);
	long _cdecl (*_res_035)(void);
	long _cdecl (*p_d_free)(long *buf, int d);
	long _cdecl (*_res_037)(void);
	long _cdecl (*_res_038)(void);
	long _cdecl (*p_d_create)(const char *path);
	long _cdecl (*p_d_delete)(const char *path);
	long _cdecl (*p_d_setpath)(const char *path);
	long _cdecl (*p_f_create)(const char *name, short attrib);
	long _cdecl (*p_f_open)(const char *name, short mode);
	long _cdecl (*p_f_close)(short fd);
	long _cdecl (*p_f_read)(short fd, long count, void *buf);

	long _cdecl (*p_f_write)(short fd, long count, const void *buf);
	long _cdecl (*p_f_delete)(const char *name);
	long _cdecl (*p_f_seek)(long place, short fd, short how);
	long _cdecl (*p_f_attrib)(const char *name, int rwflag, int attr);
	long _cdecl (*p_m_xalloc)(long size, short mode);
	long _cdecl (*p_f_dup)(short fd);
	long _cdecl (*p_f_force)(short newh, short oldh);
	long _cdecl (*p_d_getpath)(char *path, int drv);
	long _cdecl (*p_m_alloc)(long size);
	long _cdecl (*p_m_free)(void *block);
	long _cdecl (*p_m_shrink)(short dummy, void *block, long size);
	long _cdecl (*p_p_exec)(short mode, const void *ptr1, const void *ptr2, const void *ptr3);
	long _cdecl (*p_p_term)(short code);
	long _cdecl (*_res_04d)(void);
	long _cdecl (*p_f_sfirst)(const char *path, int attrib);
	long _cdecl (*p_f_snext)(void);

	long _cdecl (*_res_050)(void);
	long _cdecl (*_res_051)(void);
	long _cdecl (*_res_052)(void);
	long _cdecl (*_res_053)(void);
	long _cdecl (*_res_054)(void);
	long _cdecl (*_res_055)(void);
	long _cdecl (*p_f_rename)(short junk, const char *old, const char *new);
	long _cdecl (*p_f_datime)(ushort *timeptr, short fd, short wflag);
	long _cdecl (*_res_058)(void);
	long _cdecl (*_res_059)(void);
	long _cdecl (*_res_05a)(void);
	long _cdecl (*_res_05b)(void);
	long _cdecl (*p_f_lock)(short fd, short mode, long start, long length);
	long _cdecl (*_res_05d)(void);
	long _cdecl (*_res_05e)(void);
	long _cdecl (*_res_05f)(void);

	long _cdecl (*_res_060)(void);
	long _cdecl (*_res_061)(void);
	long _cdecl (*_res_062)(void);
	long _cdecl (*_res_063)(void);
	long _cdecl (*_res_064)(void);
	long _cdecl (*_res_065)(void);
	long _cdecl (*_res_066)(void);
	long _cdecl (*_res_067)(void);
	long _cdecl (*_res_068)(void);
	long _cdecl (*_res_069)(void);
	long _cdecl (*_res_06a)(void);
	long _cdecl (*_res_06b)(void);
	long _cdecl (*_res_06c)(void);
	long _cdecl (*_res_06d)(void);
	long _cdecl (*_res_06e)(void);
	long _cdecl (*_res_06f)(void);

	long _cdecl (*_res_070)(void);
	long _cdecl (*_res_071)(void);
	long _cdecl (*_res_072)(void);
	long _cdecl (*_res_073)(void);
	long _cdecl (*_res_074)(void);
	long _cdecl (*_res_075)(void);
	long _cdecl (*_res_076)(void);
	long _cdecl (*_res_077)(void);
	long _cdecl (*_res_078)(void);
	long _cdecl (*_res_079)(void);
	long _cdecl (*_res_07a)(void);
	long _cdecl (*_res_07b)(void);
	long _cdecl (*_res_07c)(void);
	long _cdecl (*_res_07d)(void);
	long _cdecl (*_res_07e)(void);
	long _cdecl (*_res_07f)(void);

	long _cdecl (*_res_080)(void);
	long _cdecl (*_res_081)(void);
	long _cdecl (*_res_082)(void);
	long _cdecl (*_res_083)(void);
	long _cdecl (*_res_084)(void);
	long _cdecl (*_res_085)(void);
	long _cdecl (*_res_086)(void);
	long _cdecl (*_res_087)(void);
	long _cdecl (*_res_088)(void);
	long _cdecl (*_res_089)(void);
	long _cdecl (*_res_08a)(void);
	long _cdecl (*_res_08b)(void);
	long _cdecl (*_res_08c)(void);
	long _cdecl (*_res_08d)(void);
	long _cdecl (*_res_08e)(void);
	long _cdecl (*_res_08f)(void);

	long _cdecl (*_res_090)(void);
	long _cdecl (*_res_091)(void);
	long _cdecl (*_res_092)(void);
	long _cdecl (*_res_093)(void);
	long _cdecl (*_res_094)(void);
	long _cdecl (*_res_095)(void);
	long _cdecl (*_res_096)(void);
	long _cdecl (*_res_097)(void);
	long _cdecl (*_res_098)(void);
	long _cdecl (*_res_099)(void);
	long _cdecl (*_res_09a)(void);
	long _cdecl (*_res_09b)(void);
	long _cdecl (*_res_09c)(void);
	long _cdecl (*_res_09d)(void);
	long _cdecl (*_res_09e)(void);
	long _cdecl (*_res_09f)(void);

	long _cdecl (*_res_0a0)(void);
	long _cdecl (*_res_0a1)(void);
	long _cdecl (*_res_0a2)(void);
	long _cdecl (*_res_0a3)(void);
	long _cdecl (*_res_0a4)(void);
	long _cdecl (*_res_0a5)(void);
	long _cdecl (*_res_0a6)(void);
	long _cdecl (*_res_0a7)(void);
	long _cdecl (*_res_0a8)(void);
	long _cdecl (*_res_0a9)(void);
	long _cdecl (*_res_0aa)(void);
	long _cdecl (*_res_0ab)(void);
	long _cdecl (*_res_0ac)(void);
	long _cdecl (*_res_0ad)(void);
	long _cdecl (*_res_0ae)(void);
	long _cdecl (*_res_0af)(void);

	long _cdecl (*_res_0b0)(void);
	long _cdecl (*_res_0b1)(void);
	long _cdecl (*_res_0b2)(void);
	long _cdecl (*_res_0b3)(void);
	long _cdecl (*_res_0b4)(void);
	long _cdecl (*_res_0b5)(void);
	long _cdecl (*_res_0b6)(void);
	long _cdecl (*_res_0b7)(void);
	long _cdecl (*_res_0b8)(void);
	long _cdecl (*_res_0b9)(void);
	long _cdecl (*_res_0ba)(void);
	long _cdecl (*_res_0bb)(void);
	long _cdecl (*_res_0bc)(void);
	long _cdecl (*_res_0bd)(void);
	long _cdecl (*_res_0be)(void);
	long _cdecl (*_res_0bf)(void);

	long _cdecl (*_res_0c0)(void);
	long _cdecl (*_res_0c1)(void);
	long _cdecl (*_res_0c2)(void);
	long _cdecl (*_res_0c3)(void);
	long _cdecl (*_res_0c4)(void);
	long _cdecl (*_res_0c5)(void);
	long _cdecl (*_res_0c6)(void);
	long _cdecl (*_res_0c7)(void);
	long _cdecl (*_res_0c8)(void);
	long _cdecl (*_res_0c9)(void);
	long _cdecl (*_res_0ca)(void);
	long _cdecl (*_res_0cb)(void);
	long _cdecl (*_res_0cc)(void);
	long _cdecl (*_res_0cd)(void);
	long _cdecl (*_res_0ce)(void);
	long _cdecl (*_res_0cf)(void);

	long _cdecl (*_res_0d0)(void);
	long _cdecl (*_res_0d1)(void);
	long _cdecl (*_res_0d2)(void);
	long _cdecl (*_res_0d3)(void);
	long _cdecl (*_res_0d4)(void);
	long _cdecl (*_res_0d5)(void);
	long _cdecl (*_res_0d6)(void);
	long _cdecl (*_res_0d7)(void);
	long _cdecl (*_res_0d8)(void);
	long _cdecl (*_res_0d9)(void);
	long _cdecl (*_res_0da)(void);
	long _cdecl (*_res_0db)(void);
	long _cdecl (*_res_0dc)(void);
	long _cdecl (*_res_0dd)(void);
	long _cdecl (*_res_0de)(void);
	long _cdecl (*_res_0df)(void);

	long _cdecl (*_res_0e0)(void);
	long _cdecl (*_res_0e1)(void);
	long _cdecl (*_res_0e2)(void);
	long _cdecl (*_res_0e3)(void);
	long _cdecl (*_res_0e4)(void);
	long _cdecl (*_res_0e5)(void);
	long _cdecl (*_res_0e6)(void);
	long _cdecl (*_res_0e7)(void);
	long _cdecl (*_res_0e8)(void);
	long _cdecl (*_res_0e9)(void);
	long _cdecl (*_res_0ea)(void);
	long _cdecl (*_res_0eb)(void);
	long _cdecl (*_res_0ec)(void);
	long _cdecl (*_res_0ed)(void);
	long _cdecl (*_res_0ee)(void);
	long _cdecl (*_res_0ef)(void);

	long _cdecl (*_res_0f0)(void);
	long _cdecl (*_res_0f1)(void);
	long _cdecl (*_res_0f2)(void);
	long _cdecl (*_res_0f3)(void);
	long _cdecl (*_res_0f4)(void);
	long _cdecl (*_res_0f5)(void);
	long _cdecl (*_res_0f6)(void);
	long _cdecl (*_res_0f7)(void);
	long _cdecl (*_res_0f8)(void);
	long _cdecl (*_res_0f9)(void);
	long _cdecl (*_res_0fa)(void);
	long _cdecl (*_res_0fb)(void);
	long _cdecl (*_res_0fc)(void);
	long _cdecl (*_res_0fd)(void);
	long _cdecl (*_res_0fe)(void);
	long _cdecl (*p_s_yield)(void);

	long _cdecl (*p_f_pipe)(short fds[2]);
	long _cdecl (*p_f_fchown)(short fd, short uid, short gid);
	long _cdecl (*p_f_fchmod)(short fd, ushort mode);
	long _cdecl (*p_f_sync)(short fh);
	long _cdecl (*p_f_cntl)(short fd, long arg, short cmd);
	long _cdecl (*p_f_instat)(int fh);
	long _cdecl (*p_f_outstat)(int fh);
	long _cdecl (*p_f_getchar)(int fh, int mode);
	long _cdecl (*p_f_putchar)(int fh, long c, int mode);
	long _cdecl (*p_p_wait)(void);
	long _cdecl (*p_p_nice)(short delta);
	long _cdecl (*p_p_getpid)(void);
	long _cdecl (*p_p_getppid)(void);
	long _cdecl (*p_p_getpgrp)(void);
	long _cdecl (*p_p_setpgrp)(int pid, int newgrp);
	long _cdecl (*p_p_getuid)(void);

	long _cdecl (*p_p_setuid)(unsigned short id);
	long _cdecl (*p_p_kill)(short pid, short sig);
	long _cdecl (*p_p_signal)(short sig, long handler);
	long _cdecl (*p_p_vfork)(void);
	long _cdecl (*p_p_getgid)(void);
	long _cdecl (*p_p_setgid)(unsigned short id);
	long _cdecl (*p_p_sigblock)(ulong mask);
	long _cdecl (*p_p_sigsetmask)(ulong mask);
	long _cdecl (*p_p_usrval)(long arg);
	long _cdecl (*p_p_domain)(int arg);
	long _cdecl (*p_p_sigreturn)(void);
	long _cdecl (*p_p_fork)(void);
	long _cdecl (*p_p_wait3)(short nohang, long *rusage);
	long _cdecl (*p_f_select)(unsigned short timeout, long *rfdp, long *wfdp, long *xfdp);
	long _cdecl (*p_p_rusage)(long *r);
	long _cdecl (*p_p_setlimit)(short i, long v);

	long _cdecl (*p_t_alarm)(long x);
	long _cdecl (*p_p_pause)(void);
	long _cdecl (*p_s_ysconf)(int which);
	long _cdecl (*p_p_sigpending)(void);
	long _cdecl (*p_d_pathconf)(const char *name, int which);
	long _cdecl (*p_p_msg)(int mode, long mbid, char *ptr);
	long _cdecl (*p_f_midipipe)(short pid, short in, short out);
	long _cdecl (*p_p_renice)(short pid, short increment);
	long _cdecl (*p_d_opendir)(const char *path, int flags);
	long _cdecl (*p_d_readdir)(int len, long handle, char *buf);
	long _cdecl (*p_d_rewind)(long handle);
	long _cdecl (*p_d_closedir)(long handle);
	long _cdecl (*p_f_xattr)(int flag, const char *name, struct xattr *xattr);
	long _cdecl (*p_f_link)(const char *old, const char *new);
	long _cdecl (*p_f_symlink)(const char *old, const char *new);
	long _cdecl (*p_f_readlink)(int buflen, char *buf, const char *linkfile);

	long _cdecl (*p_d_cntl)(int cmd, const char *name, long arg);
	long _cdecl (*p_f_chown)(const char *name, int uid, int gid);
	long _cdecl (*p_f_chmod)(const char *name, unsigned short mode);
	long _cdecl (*p_p_umask)(ushort mode);
	long _cdecl (*p_p_semaphore)(int mode, long id, long timeout);
	long _cdecl (*p_d_lock)(int mode, int drv);
	long _cdecl (*p_p_sigpause)(ulong mask);
	long _cdecl (*p_p_sigaction)(short sig, const struct sigaction *act, struct sigaction *oact);
	long _cdecl (*p_p_geteuid)(void);
	long _cdecl (*p_p_getegid)(void);
	long _cdecl (*p_p_waitpid)(short pid, short nohang, long *rusage);
	long _cdecl (*p_d_getcwd)(char *path, int drv, int size);
	long _cdecl (*p_s_alert)(const char *msg);
	long _cdecl (*p_t_malarm)(long x);
	long _cdecl (*_p_p_sigintr)(void);
	long _cdecl (*p_s_uptime)(ulong *cur_uptim, ulong loadave[3]);

	long _cdecl (*p_p_trace)(short request, short pid, void *addr, long data);
	long _cdecl (*p_m_validate)(short pid, void *addr, long size, long *flags);
	long _cdecl (*p_d_xreaddir)(int len, long handle, char *buf, struct xattr *xattr, long *xret);
	long _cdecl (*p_p_seteuid)(unsigned short id);
	long _cdecl (*p_p_setegid)(unsigned short id);
	long _cdecl (*p_p_getauid)(void);
	long _cdecl (*p_p_setauid)(int id);
	long _cdecl (*p_p_getgroups)(short gidsetlen, unsigned short gidset[]);
	long _cdecl (*p_p_setgroups)(short gidsetlen, unsigned short gidset[]);
	long _cdecl (*p_t_setitimer)(int which, long *interval, long *value, long *ointerval, long *ovalue);
	long _cdecl (*p_d_chroot)(const char *dir);
	long _cdecl (*p_f_stat64)(int flag, const char *name, struct stat *stat);
	long _cdecl (*p_f_seek64)(llong place, short fd, short how, llong *newpos);
	long _cdecl (*p_d_setkey)(llong dev, char *key, int cipher);
	long _cdecl (*p_p_setreuid)(unsigned short rid, unsigned short eid);
	long _cdecl (*p_p_setregid)(unsigned short rid, unsigned short eid);

	long _cdecl (*p_s_ync)(void);
	long _cdecl (*p_s_hutdown)(long restart);
	long _cdecl (*p_d_readlabel)(const char *path, char *label, int maxlen);
	long _cdecl (*p_d_writelabel)(const char *path, const char *label);
	long _cdecl (*p_s_system)(int mode, ulong arg1, ulong arg2);
	long _cdecl (*p_t_gettimeofday)(struct timeval *tv, struct timezone *tz);
	long _cdecl (*p_t_settimeofday)(struct timeval *tv, struct timezone *tz);
	long _cdecl (*p_t_adjtime)(const struct timeval *delta, struct timeval *olddelta);
	long _cdecl (*p_p_getpriority)(short which, short who);
	long _cdecl (*p_p_setpriority)(short which, short who, short prio);
	long _cdecl (*p_f_poll)(struct pollfd *fds, ulong nfds, ulong timeout);
	long _cdecl (*p_f_writev)(short fd, const struct iovec *iov, long niov);
	long _cdecl (*p_f_readv)(short fd, const struct iovec *iov, long niov);
	long _cdecl (*p_f_fstat)(short fd, struct stat *st);
	long _cdecl (*p_p_sysctl)(long *name, ulong namelen, void *old, ulong *oldlenp, const void *new, ulong newlen);
	long _cdecl (*p_s_emulation)(ushort which, ushort op, long a1, long a2, long a3, long a4, long a5, long a6, long a7);

	long _cdecl (*p_f_socket)(long domain, long type, long protocol);
	long _cdecl (*p_f_socketpair)(long domain, long type, long protocol, short fds[2]);
	long _cdecl (*p_f_accept)(short fd, struct sockaddr *addr, long *addrlen);
	long _cdecl (*p_f_connect)(short fd, const struct sockaddr *addr, long addrlen);
	long _cdecl (*p_f_bind)(short fd, struct sockaddr *addr, long addrlen);
	long _cdecl (*p_f_listen)(short fd, long backlog);
	long _cdecl (*p_f_recvmsg)(short fd, struct msghdr *msg, long flags);
	long _cdecl (*p_f_sendmsg)(short fd, const struct msghdr *msg, long flags);
	long _cdecl (*p_f_recvfrom)(short fd, char *buf, long buflen, long flags, struct sockaddr *addr, long *addrlen);
	long _cdecl (*p_f_sendto)(short fd, char *buf, long buflen, long flags, const struct sockaddr *addr, long addrlen);
	long _cdecl (*p_f_setsockopt)(short fd, long level, long optname, void *optval, long optlen);
	long _cdecl (*p_f_getsockopt)(short fd, long level, long optname, void *optval, long *optlen);
	long _cdecl (*p_f_getpeername)(short fd, struct sockaddr *addr, long *addrlen);
	long _cdecl (*p_f_getsockname)(short fd, struct sockaddr *addr, long *addrlen);
	long _cdecl (*p_f_shutdown)(short fd, long how);
	long _cdecl (*_res_16f)(void);

	long _cdecl (*p_p_shmget)(long key, long size, long shmflg);
	long _cdecl (*p_p_shmctl)(long shmid, long cmd, struct shmid_ds *buf);
	long _cdecl (*p_p_shmat)(long shmid, const void *shmaddr, long shmflg);
	long _cdecl (*p_p_shmdt)(const void *shmaddr);
	long _cdecl (*p_p_semget)(long key, long nsems, long semflg);
	long _cdecl (*p_p_semctl)(long semid, long semnum, long cmd, union __semun *arg);
	long _cdecl (*p_p_semop)(long semid, struct sembuf *sops, long nsops);
	long _cdecl (*p_p_semconfig)(long flag);
	long _cdecl (*p_p_msgget)(long key, long msgflg);
	long _cdecl (*p_p_msgctl)(long msqid, long cmd, struct msqid_ds *buf);
	long _cdecl (*p_p_msgsnd)(long msqid, const void *msgp, long msgsz, long msgflg);
	long _cdecl (*p_p_msgrcv)(long msqid, void *msgp, long msgsz, long msgtyp, long msgflg);
	long _cdecl (*_res_17c)(void);
	long _cdecl (*p_m_access)(void *addr, long size, short mode);
	long _cdecl (*p_m_map)(void);
	long _cdecl (*p_munmap)(void);

	long _cdecl (*p_f_chown16)(const char *name, int uid, int gid, int follow_symlinks);
	long _cdecl (*p_f_chdir)(short fd);
	long _cdecl (*p_f_opendir)(short fd);
	long _cdecl (*p_f_dirfd)(long handle);
	long _cdecl (*_res_184)(void);
	long _cdecl (*_res_185)(void);
	long _cdecl (*_res_186)(void);
	long _cdecl (*_res_187)(void);
	long _cdecl (*_res_188)(void);
	long _cdecl (*_res_189)(void);
	long _cdecl (*_res_18a)(void);
	long _cdecl (*_res_18b)(void);
	long _cdecl (*_res_18c)(void);
	long _cdecl (*_res_18d)(void);
	long _cdecl (*_res_18e)(void);
	long _cdecl (*_res_18f)(void);

} dos_vecs;

#endif
