#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = rezchg

srcdir = .
top_srcdir = ..
subdir = xam

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
