#
# Makefile for MiNT tools
#

SHELL = /bin/sh
SUBDIRS = \
	IO \
	crypto \
	fdisk \
	fsetter \
	gluestik \
	lpflush \
	mgw \
	minix \
	mintload \
	mkfatfs \
	mktbl \
	net-tools \
	nfs \
	nohog2 \
	ps \
	strace \
	swkbdtbl \
	sysctl \
	usbtool

srcdir = .
top_srcdir = .
subdir = tools

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
