#
# Makefile for MiNT tools
#

SHELL = /bin/sh
SUBDIRS = IO crypto fdisk fsetter gluestik mgw \
		minix mkfatfs net-tools sysctl toswin2

srcdir = .
top_srcdir = .
subdir = tools

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
