.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) Guido Flohr (gufl0000@stud.uni-sb.de), Oct 19, 1999
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the MiNT kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH DCHROOT 2 "19 October 1999" "FreeMiNT 1.15.2b" "FreeMiNT Programmer's Manual"
.SH NAME
Dchroot \- change root directory
.SH SYNOPSIS
.B #include <mintbind.h>
.sp
.BI "long Dchroot (const char* " path );
.SH DESCRIPTION
.B Dchroot
is the underlying kernel call for
.BR chroot (2).

.SH "SEE ALSO"
.BR chroot (2)
