.TH Dgetcwd 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"

.SH NAME
Dgetcwd \- get current working directory for a process

.SH SYNOPSIS
.nf
LONG Dgetcwd(char *path, WORD drv, WORD size);
.fi

.SH DESCRIPTION
.I Dgetcwd
may be used to retrieve the current working directory on the
indicated drive for the current process. The directory is
copied into the buffer pointed to by
.IR path ,
which is at lest
.I size
bytes long.

.SH RETURNS
0 on success
.PP
ERANGE if the supplied buffer is not long enough to hold the path
.PP
EDRIVE if
.I drv
is not a valid GEMDOS drive.

.SH "SEE ALSO"
.IR Dgetpath (2)

