.TH Dreadlabel 2 "MiNT Programmer's Manual" "Version 1.11" "Nov 11, 1994"
.SH NAME
Dreadlabel \- read filesystem label
.SH SYNOPSIS
.nf
LONG Dreadlabel ( const char *path, char *label, WORD length );
.fi
.SH DESCRIPTION
.I Dreadlabel
returns the label for the filesystem specified by
.IR name 
in
.IR label .
.I length
specifies the length of the buffer to which
.IR label
is pointing. Note that not all filesystems have labels. Examples are the 
DOS or TOS filesystem, the Mac HFS filesystem and the ISO9660 filesystem 
for CD ROMs.
.SH RETURNS
0 if successful,
ENAMETOOLONG if the label won't fit into the buffer,
EFILNF if no label present,
or another appropiate GEMDOS error code.
.SH "SEE ALSO"
.IR Dwritelabel (2)
