.TH Drewinddir 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Drewinddir \- rewind an open directory
.SH SYNOPSIS
.nf
LONG Drewinddir( LONG handle );
.fi
.SH DESCRIPTION
.I Drewinddir
rewinds the open directory whose handle (returned from the
.I Dopendir
system call) is
.IR handle .
After the
.I Drewinddir
call, the next call to
.I Dreaddir
will read the first file in the directory.
.SH RETURNS
0 on success.
.PP
EIHNDL if
.I handle
does not refer to a valid open directory
.PP
EINVFN if the directory cannot be rewound (for example, because of
the type of file system on which it is located)
.SH "SEE ALSO"
.IR Dopendir (2),
.IR Dreaddir (2),
