.TH Finstat 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Finstat \- determine input status for a file
.SH SYNOPSIS
.nf
LONG Finstat( WORD fh );
.fi
.SH DESCRIPTION
.I Finstat
returns the number of bytes of input waiting on the file whose
GEMDOS handle is
.IR fh ,
or 0 if no input is available on that handle.
.SH RETURNS
0 or a positive number if successful
.PP
EIHNDL if
.I fh
is not a valid handle for an open file.
.SH "SEE ALSO"
.IR Cauxis (2),
.IR Cconis (2),
.IR Fcntl (2),
.IR Foutstat (2)
.SH BUGS
Always returns 1 for disk files.
.PP
Doesn't check to see if the indicated file was opened for reading.
