.TH Foutstat 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Foutstat \- determine output status for a file
.SH SYNOPSIS
.nf
LONG Foutstat( WORD fh );
.fi
.SH DESCRIPTION
.I Foutstat
returns the number of bytes of output that may be written to the
file whose GEMDOS handle is
.IR fh ,
without blocking.
.SH RETURNS
0 or a positive number if successful
.PP
EIHNDL if
.I fh
is not a valid handle for an open file.
.SH "SEE ALSO"
.IR Cauxos (2),
.IR Cconos (2),
.IR Cprnos (2),
.IR Fcntl (2),
.IR Finstat (2)
.SH BUGS
Always returns 1 for disk files.
.PP
Doesn't check to see if the indicated file was opened for writing.
