.TH Pdomain 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Pdomain \- get or set process execution domain
.SH SYNOPSIS
.nf
WORD Pdomain( WORD dom );
.fi
.SH DESCRIPTION
.I Pdomain
gets or sets the process execution domain. This is a number which controls
the behavior of a process. The default domain is 0, which is the TOS
compatibility domain and in which all system calls behave exactly as they
do under TOS. Domain 1 is the MiNT domain; in this domain, the behavior of
the
.I Fread
and
.I Fwrite
system calls when applied to terminals are controlled by the current terminal
settings as established by the
.I Fcntl
system call. Moreover, file names returned from
.I Fsfirst
and
.I Fsnext
may be treated differently; MiNT domain processes are expected to be able
to deal with file names that are not standard 8 character name + 3 character
extension, all upper case, DOS file names.
.PP
If
.I dom
is greater than or equal to 0, the process domain is set to its value. Note
that only domains 0 and 1 are currently defined, and the result of using
a different (positive) number for
.I dom
is unpredictable. If
.I dom
is negative, no change is made to the process domain.
.SH RETURNS
The process domain at the time of the
.I Pdomain
call (i.e. before any change).
