.TH Pgetpid 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Pgetpid \- get the current process id
.SH SYNOPSIS
.nf
WORD Pgetpid();
.fi
.SH DESCRIPTION
.I Pgetpid
returns the process id of the currently running process. This is a positive
16 bit integer which is unique among all processes currently in
the system. The call is always successful.
.SH "SEE ALSO"
.IR Pgetpgrp (2),
.IR Pgetppid (2)
