.TH Pgetppid 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Pgetppid \- get the process id for the parent of the current process
.SH SYNOPSIS
.nf
WORD Pgetppid();
.fi
.SH DESCRIPTION
.I Pgetppid
returns the process id of the parent of the currently running process.
The process id is a positive
16 bit integer. The call is always successful.
.SH "SEE ALSO"
.IR Pgetpgrp (2),
.IR Pgetpid (2)
.SH NOTES
If the current process was started directly by the kernel, then
.I Pgetppid
will return 0.
