.TH Pnice 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Pnice \- change process priority for the current process
.SH SYNOPSIS
.nf
WORD Pnice( WORD delta );
.fi
.SH DESCRIPTION
.I Pnice
changes the base process niceness for the current process
by the amount
.IR delta .
Higher levels of niceness correspond to decreased priority in scheduling,
so positive values for delta cause the corresponding process to be
scheduled less often. Conversely, negative values for delta cause the
process priority to be increased.
.SH RETURNS
The (adjusted) process priority, as a 16 bit signed integer.
0 is the default priority; values greater
than 0 are for higher priority processes (ones that are scheduled more often),
and values less than 0 are lower priority processes.
.SH "SEE ALSO"
.IR Prenice (2)
.SH BUGS
The scheduling algorithm is pretty weird, so it's hard to predict exactly
what effect process priorities have.
