.TH Prenice 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Prenice \- change process priority
.SH SYNOPSIS
.nf
LONG Prenice( WORD pid, WORD delta );
.fi
.SH DESCRIPTION
.I Prenice
changes the base process niceness for process
.I pid
by the amount
.IR delta .
Higher levels of niceness correspond to decreased priority in scheduling,
so positive values for delta cause the corresponding process to be
scheduled less often. Conversely, negative values for delta cause the
process priority to be increased.
.SH RETURNS
The current priority for the process, if successful. This is a 16 bit
signed quantity. The default priority is 0; higher priority processes have
larger priority values, lower priority ones have smaller values.
.PP
EFILNF if the indicated process does not exist (note that since this is
a 32 bit negative number it can be distinguished from the WORD negative
numbers returned for low priority processes)
.PP
EACCDN if the process has a different user id
.SH "SEE ALSO"
.IR Pnice (2)
.SH BUGS
The scheduling algorithm is pretty weird, so it's hard to predict exactly
what effect process priorities have.

