.TH Prusage 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Prusage \- get resource usage information
.SH SYNOPSIS
.nf
void Prusage( LONG *r );
.fi
.SH DESCRIPTION
.I Prusage
puts information on resources used by the process into the memory pointed
to by
.IR r ,
as follows:
.nf
   r[0]: time spent by process in MiNT kernel
   r[1]: time spent by process in its own code
   r[2]: total kernel time spent by children of this process
   r[3]: total user code time spent by children of this process
   r[4]: memory allocated to this process (bytes)
   r[5]-r[7]: reserved for future use
.fi
All times are in milliseconds.
.SH "SEE ALSO"
.IR Psetlimit (2)
