.TH Psigpending 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Psigpending \- determine which signals have been sent but not delivered
.SH SYNOPSIS
.nf
LONG Psigpending();
.fi
.SH DESCRIPTION
.I Psigpending
returns a bit mask containing the signals that have been sent to the calling
process but not yet delivered (probably because they have blocked, either
directly via
.I Psigblock
or
.IR Psigsetmask ,
or indirectly because of signal handling.
.SH RETURNS
Bit
.I n
of the returned value is set if (and only if) signal number
.I n
is pending.
.SH "SEE ALSO"
.IR Psigblock (2),
.IR Psignal (2),
.IR Psigsetmask (2)
