.TH Pusrval 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Pusrval \- get or set process specific information
.SH SYNOPSIS
.nf
LONG Pusrval(LONG val);
.fi
.SH DESCRIPTION
.I Pusrval
may be used to set or retrieve the old process specific user value. This is
a long word which is attached to the process, and is inherited by child
processes. The use and meaning of the value is entirely up to applications;
the kernel only records it.
.PP
If
.I val
is -1 no change is made to the user value; otherwise it is set to
.IR val .
.SH RETURNS
The old process specific user value.
.SH "SEE ALSO"
.SH BUGS
-1 cannot be used as a user value.
