.TH Salert 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"

.SH NAME
Salert \- print a warning or error message

.SH SYNOPSIS
.nf
void Salert( char *msg );
.fi

.SH DESCRIPTION
.I Salert
sends a warning or error message to the alert pipe, U:\\PIPE\\ALERT.
The argument
.I msg
is a 0 terminated ASCII string containing the message to be sent. The
message should not contain any carriage return, line feed, or
escape characters; it should be a simple one line warning or
error message which is to be brought to the user's attention.
The
.I Salert
call takes whatever steps are necessary to format this string
and send it to the user; the exact form of the output (or even
whether the output is seen at all) depends on the system
configuration.

.SH "SEE ALSO"
.IR Cconws (2)

.SH BUGS
The message is not guaranteed to be delivered to the user
(users may turn alert messages off). Therefore, absolutely critical or
fatal errors should be delivered to the user in a different
fashion.

.PP
Messages longer than 90 characters may be truncated; also, if any
word in the message is longer than 30 characters it may not be printed
in full (a word is any sequence of non-blank characters).
