.TH Syield 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Syield \- give up the processor
.SH SYNOPSIS
.nf
void Syield();
.fi
.SH DESCRIPTION
.I Syield
gives up control of the processor temporarily.
.SH "SEE ALSO"
.IR Pause (2),
.IR Fselect (2)
.SH BUGS
Doing
.I Syield
in a tight loop can still consume a fair amount of processor time.
Use
.I Fselect
or
.I Talarm
and
.I Pause
instead if possible.
