.TH Sysconf 2 "MiNT Programmer's Manual" "Version 1.0" "Feb. 1, 1993"
.SH NAME
Sysconf \- get information about operating system configuration
.SH SYNOPSIS
.nf
LONG Sysconf( WORD n );
.fi
.SH DESCRIPTION
.I Sysconf
returns information about various limits or capabilities of the currently
running version of MiNT. The variable
.I n
controls which limit or capability is being queried, as follows:
.nf
        n	Value Returned

	-1	return max. legal value for n in Sysconf(n)
	0	return max. number of memory regions per process
	1	return max. length of Pexec() command line string
	2	return max. number of open files per process
	3	return number of supplementary group id's
	4	return max. number of processes per user
.fi
If any of these items are unlimited, then 0x7fffffffL is returned.
.SH "SEE ALSO"
.IR Dpathconf (2)
