#
# Makefile for minixfs tools
#
SHELL = /bin/sh
SUBDIRS = docs fsck minit tools

srcdir = .
top_srcdir = ..
subdir = minix

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here:

# default overwrites

# default definitions
